apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-metric
    labels:
      app: nginx-metric
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-metric
  template:
    metadata:
      labels:
        app: nginx-metric
    spec:
      containers:
      - name: nginx-metric
        image: dookee/nginx-metric:1.0
        ports:
        - containerPort: 80
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        env:
          - name: SCRAPE_URI
            value: "http://127.0.0.1:8080/basic_status"
        ports:
        - containerPort: 9113
