apiVersion: v1
kind: Service
metadata:
  name: nginx-metric
  labels:
    app: nginx-metric
spec:
  selector:
    app: nginx-metric
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-prometheus-exporter
    port: 9113
    protocol: TCP
    targetPort: 9113
