apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: hipster-shop-stage
commonLabels:
  environment: stage
images:
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: v0.1.3
bases:
- ../../main
