apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
  namespace: dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ken
