apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
    spec:
      containers:
      - image: bitnami/node-exporter:latest
        imagePullPolicy: IfNotPresent
        name: prometheus-node-exporter
      hostNetwork: true
